CREATE TABLE item (
id INT AUTO_INCREMENT Primary Key,
category VARCHAR(50) NOT NULL,
img text NOT NULL,
name VARCHAR(200) NOT NULL,
descript text NOT NULL,
price INT NOT NULL,
post INT NOT NULL,
boon text NOT NULL,
discount text,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);