CREATE TABLE item (
id int AUTO_INCREMENT NOT NULL PRIMARY KEY,
img text NOT NULL,
name text NOT NULL,
descript text NOT NULL,
price text NOT NULL,
post text NOT NULL,
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);